uvmf:
  environments:
    "execute" :
      imports :
        - name: "lc3_prediction_pkg"
      ## Agents are defined in a LIST so that the order is maintained. This is important
      ## because of how the BFMs are passed in at the bench utilize this same order when
      ## this environment's initialize() routine is called.
      agents :
        - name: "execute_in_agent" 
          type: "execute_in"
        - name: "execute_out_agent"
          type: "execute_out"
      ## Analysis components are defined externally in a 'util_components' structure.
      ## They are instantiated here.
      analysis_components :
        - name: "execute_pred"
          type: "execute_predictor"
      ## Each scoreboard is keyed by the scoreboard instantiation name with
      ## information on the scoreboard type and what type of transaction it
      ## will be parsing
      scoreboards : 
        - name: "execute_scoreboard"
          sb_type: "uvmf_in_order_scoreboard"
          trans_type: "execute_out_transaction"
      ## Define internal TLM connections. Each entry must have a 'driver' and
      ## a 'receiver' entry used to determine the full connection.
      tlm_connections :
        # Connection 0
        - driver:   "execute_in_agent.monitored_ap"
          receiver: "execute_pred.execute_in_agent_ae"
        # Connection 1
        - driver:   "execute_pred.execute_in_sb_ap"
          receiver: "execute_scoreboard.expected_analysis_export"
        # Connection 2
        - driver:   "execute_out_agent.monitored_ap"
          receiver: "execute_scoreboard.actual_analysis_export"
  util_components:
    "execute_predictor" :  
      type: "predictor"
      analysis_exports :
        - name: "execute_in_agent_ae"
          type: "execute_in_transaction"
      analysis_ports : 
        - name: "execute_in_sb_ap"
          type: "execute_out_transaction"

